# Generated by Django 5.1.7 on 2025-06-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_norm'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='norm',
            table='norma',
        ),
        migrations.AlterModelTable(
            name='platform',
            table='plataforma',
        ),
    ]
