# Generated by Django 5.1.7 on 2025-07-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_norm_table_alter_platform_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norm',
            options={'ordering': ['Nome']},
        ),
        migrations.RenameField(
            model_name='norm',
            old_name='link',
            new_name='Direcionamento',
        ),
        migrations.RenameField(
            model_name='norm',
            old_name='name',
            new_name='Nome',
        ),
        migrations.RemoveField(
            model_name='norm',
            name='id',
        ),
        migrations.AddField(
            model_name='norm',
            name='id_norma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
