# Generated by Django 5.1.7 on 2025-07-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_norm_options_rename_link_norm_direcionamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norm',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='norm',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='norm',
            name='updated_at',
        ),
    ]
