# Generated by Django 5.1.7 on 2025-07-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_norm_created_at_remove_norm_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['Nome']},
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='link',
            new_name='Direcionamento',
        ),
        migrations.RenameField(
            model_name='platform',
            old_name='name',
            new_name='Nome',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='id',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='platform',
            name='id_plataforma',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
