# Generated by Django 5.1.7 on 2025-08-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_platform_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "Administrador"),
                    ("MANAGER", "Gestor"),
                    ("COMMON", "Usuário"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="cidade",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
