# Generated by Django 5.0.3 on 2025-09-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISO37120Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('nome_indicador', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('core', 'Principal'), ('supporting', 'Apoio'), ('profile', 'Perfil')], max_length=20)),
                ('ods', models.CharField(max_length=10)),
                ('unidade', models.CharField(max_length=50)),
                ('dado_2022', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2023', models.CharField(blank=True, max_length=100, null=True)),
                ('dado_2024', models.CharField(blank=True, max_length=100, null=True)),
                ('fonte_2022', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2023', models.CharField(blank=True, max_length=500, null=True)),
                ('fonte_2024', models.CharField(blank=True, max_length=500, null=True)),
                ('cidade', models.CharField(default='Londrina', max_length=100)),
                ('estado', models.CharField(default='PR', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iso37120_indicators',
                'ordering': ['categoria', 'nome_indicador'],
                'unique_together': {('nome_indicador', 'cidade', 'estado')},
            },
        ),
    ]
