# Generated by Django 5.2.7 on 2025-11-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_iso37122indicator_iso37123indicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso37120indicator',
            name='dado_2025',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iso37120indicator',
            name='fonte_2025',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='iso37122indicator',
            name='dado_2025',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iso37122indicator',
            name='fonte_2025',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='iso37123indicator',
            name='dado_2025',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iso37123indicator',
            name='fonte_2025',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='iso37125indicator',
            name='dado_2025',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iso37125indicator',
            name='fonte_2025',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
