# Generated by Django 5.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_iso37120indicator_dado_2025_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso37120indicator',
            name='anexo_2022',
            field=models.FileField(blank=True, null=True, upload_to='iso37120/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37120indicator',
            name='anexo_2023',
            field=models.FileField(blank=True, null=True, upload_to='iso37120/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37120indicator',
            name='anexo_2024',
            field=models.FileField(blank=True, null=True, upload_to='iso37120/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37120indicator',
            name='anexo_2025',
            field=models.FileField(blank=True, null=True, upload_to='iso37120/anexos/'),
        ),
    ]
