# Generated by Django 5.2.8 on 2025-11-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_anexo_fields_iso37120'),
    ]

    operations = [
        migrations.AddField(
            model_name='iso37122indicator',
            name='anexo_2022',
            field=models.FileField(blank=True, null=True, upload_to='iso37122/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37122indicator',
            name='anexo_2023',
            field=models.FileField(blank=True, null=True, upload_to='iso37122/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37122indicator',
            name='anexo_2024',
            field=models.FileField(blank=True, null=True, upload_to='iso37122/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37122indicator',
            name='anexo_2025',
            field=models.FileField(blank=True, null=True, upload_to='iso37122/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37123indicator',
            name='anexo_2022',
            field=models.FileField(blank=True, null=True, upload_to='iso37123/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37123indicator',
            name='anexo_2023',
            field=models.FileField(blank=True, null=True, upload_to='iso37123/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37123indicator',
            name='anexo_2024',
            field=models.FileField(blank=True, null=True, upload_to='iso37123/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37123indicator',
            name='anexo_2025',
            field=models.FileField(blank=True, null=True, upload_to='iso37123/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37125indicator',
            name='anexo_2022',
            field=models.FileField(blank=True, null=True, upload_to='iso37125/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37125indicator',
            name='anexo_2023',
            field=models.FileField(blank=True, null=True, upload_to='iso37125/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37125indicator',
            name='anexo_2024',
            field=models.FileField(blank=True, null=True, upload_to='iso37125/anexos/'),
        ),
        migrations.AddField(
            model_name='iso37125indicator',
            name='anexo_2025',
            field=models.FileField(blank=True, null=True, upload_to='iso37125/anexos/'),
        ),
    ]
